// THIS IS A COMPILED FILE. DO NOT EDIT THIS FILE 
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "format", {
    enumerable: true,
    get: function() {
        return format;
    }
});
function format(a, b) {
    return `${a} ${b}`;
}
