// THIS IS A COMPILED FILE. DO NOT EDIT THIS FILE 
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
const _lib = require("C:/Projects/hades/resources/[compiled]/framework/modules/test/server/lib.js");
console.log((0, _lib.format)('Hello', 'World'));
